os: linux
dist: bionic
language: minimal
services:
  - docker

env:
  global:
    - seafile_version=7.1.5 seafile_arch=aarch64
  jobs:
#    - DOCKERFILE=Dockerfile DOCKER_IMAGE_TAG="${seafile_version}-${seafile_arch}" SEAFILE_BIN="seafile-server_${seafile_version}_${seafile_arch}.tar.gz"
    - DOCKERFILE=Dockerfile.alpine DOCKER_IMAGE_TAG="${seafile_version}-${seafile_arch}-alpine" SEAFILE_BIN="seafile-server_${seafile_version}_${seafile_arch}-alpine.tar.gz"

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx

before_script:
  - curl -L -O "https://github.com/hanwckf/seafile-aarch64-build/releases/download/v${seafile_version}-server/$SEAFILE_BIN"

script:
  - sh build.sh

after_success:
  - docker images

deploy:
  provider: script
  script: sh travis-ci/docker_push.sh
  on:
    repo: hanwckf/seafile-aarch64-docker
    tags: true

