os: linux
dist: bionic
virt: lxd
arch: arm64-graviton2
group: edge
language: minimal
services:
  - docker

env:
  global:
    - seafile_version=7.1.5 seafile_arch=aarch64
  jobs:
#    - DOCKERFILE=Dockerfile DOCKER_IMAGE_TAG="${seafile_version}-${seafile_arch}" SEAFILE_BIN="seafile-server_${seafile_version}_${seafile_arch}.tar.gz"
    - DOCKERFILE=Dockerfile.alpine DOCKER_IMAGE_TAG="${seafile_version}-${seafile_arch}-alpine" SEAFILE_BIN="seafile-server_${seafile_version}_${seafile_arch}-alpine.tar.gz"

before_script:
  - curl -L -O "https://github.com/hanwckf/seafile-arm64-build/releases/download/v${seafile_version}-server/$SEAFILE_BIN"

script:
  - sh build.sh

after_success:
  - docker images

deploy:
  provider: script
  script: sh travis-ci/docker_push.sh
  on:
    repo: hanwckf/seafile-arm64-docker
    tags: true
